In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [45]:
X=[1,2]
print(X)
Y=[2,3]
print(Y)

[1, 2]
[2, 3]


In [46]:
Z=X+Y

In [47]:
print(Z)

[1, 2, 2, 3]


In [48]:
X=np.array([1,2])
Y=np.array([3,4])
D=X+Y
E=np.add(X,Y)
F=np.sum(X+Y)
print(D)
print(E)
print(F)

[4 6]
[4 6]
10


In [49]:
#calculate the eucledian distance between the numpy arrays
X=np.array([1,2])
Y=np.array([3,4])
(X-Y)**2
distance=np.sqrt(np.sum((X-Y)**2))
print(distance)

2.8284271247461903


In [60]:
#multiplication of numpy arrays
X=np.array([1,2])
Y=np.array([3,4])
print(X.ndim)
print(Y.ndim)
print(X.shape)
print(Y.shape)
# the transpositon does not work on 1d array
print(X.shape)
print(X.ndim)
print(X)

1
1
(2,)
(2,)
(2,)
1
[1 2]


In [77]:
# if we give same dimensons then we get a matrix but if we give a different dimensions then we get a list at each index
X=np.array([[1,2,3],[2,4,3]])
Y=np.array([[1,2,3],[[2,3]]])
print(X)
print(Y)

[[1 2 3]
 [2 4 3]]
[list([1, 2, 3]) list([[2, 3]])]


In [78]:
# we can only perform the simple add operation in list
Y[0]+Y[1]

[1, 2, 3, [2, 3]]

In [7]:
X=np.array([[1,2],[3,4]])
Y=np.array([[5,6],[7,8]])
np.add(X,Y)

array([[ 6,  8],
       [10, 12]])

In [9]:
X=np.array([[1,2],[3,4]])
Y=np.array([[5,6],[7,8]])
np.subtract(X,Y)

array([[-4, -4],
       [-4, -4]])

In [12]:
X=np.array([[1,2],[3,4]])
Y=np.array([[5,6],[7,8]])
np.multiply(X,Y)

array([[ 5, 12],
       [21, 32]])

In [19]:
print(X.T)
print(X)
print(Y)

[[1 3]
 [2 4]]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [18]:
np.dot(X,Y)

array([[19, 22],
       [43, 50]])

In [20]:
X.dot(Y)

array([[19, 22],
       [43, 50]])

In [21]:
print(X)
print(Y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [31]:
X=np.random.rand(5)
print(X)

[0.02851235 0.24554619 0.71961315 0.7662381  0.61797083]


In [34]:
#it makes a nd array of given dimnsion in tuple
X=np.random.rand(5,5)
print(X)

[[0.55100637 0.30105894 0.48922208 0.58980931 0.24847384]
 [0.71926139 0.15361941 0.85203426 0.32710313 0.19813273]
 [0.75811096 0.33035473 0.93080279 0.32740067 0.77299512]
 [0.25366245 0.1731196  0.22420002 0.26231996 0.51361464]
 [0.25918666 0.9968324  0.29007758 0.78603683 0.53560033]]


In [44]:
X=np.random.sample((2,3))
print(X)
X=np.random.sample((2,3))+10
print(X)

[[0.78902958 0.26869242 0.1724024 ]
 [0.57936171 0.88887003 0.96959645]]
[[10.05971541 10.23441336 10.2734266 ]
 [10.99195793 10.3902859  10.52519099]]


In [53]:
#it will return the nd array of given shape where range of int is between 0 and given int in this case between 0 and 2
np.random.randint(2,size=(3,2))

array([[1, 1],
       [1, 0],
       [0, 0]])

In [54]:
X=np.random.random_sample((2,3))
print(X)
X=np.random.random_sample((2,3))+10
print(X)

[[0.93921927 0.93470094 0.22064743]
 [0.12761372 0.29284062 0.91625187]]
[[10.7554411  10.93314681 10.37021111]
 [10.5338672  10.3648724  10.48996539]]


In [55]:
plt.scatter?

In [62]:
X=np.array([1,2,3,4,5,6,7])
print(np.argmin(X))
print(np.argmax(X))
print(np.max(X))
print(np.maximum?

0
6
7
