In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
a.ndim

1

In [4]:
a.shape

(5,)

In [5]:
b=a[1:]
print(b)

[2 3 4 5]


In [6]:
b[0]=20
print(a)
print(b)

[ 1 20  3  4  5]
[20  3  4  5]


In [7]:
np.shares_memory(a,b)

True

In [9]:
twod=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twod)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
twod.shape

(3, 3)

In [11]:
twod.ndim

2

In [13]:
b=twod[:,:]
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
b=twod[:2]
print(b)

[[1 2 3]
 [4 5 6]]


In [18]:
zeroes=np.zeros(3,dtype="int64")
print(zeroes)

[0 0 0]


In [22]:
ones=np.ones([3,3],dtype="int64")
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [24]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
a=np.array([[11,2],[3,4]])
b=np.array([[5,6],[9,80]])

In [27]:
a+b

array([[ 6,  8],
       [10, 12]])

In [28]:
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [29]:
a*b

array([[ 5, 12],
       [21, 32]])

In [30]:
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [34]:
dot=np.dot(a,b)
print(dot)

[[19 22]
 [43 50]]


In [49]:
print(a.argmax())
print(b.argmax())

3
3


In [52]:
print(a.argsort())

[[1 0]
 [0 1]]


In [58]:
diag=np.diag([3,3,3])
print(diag)

[[3 0 0]
 [0 3 0]
 [0 0 3]]


In [59]:
array=np.random.rand(10)
print(array)

[0.99540836 0.43892102 0.62117016 0.6256223  0.69708828 0.63657594
 0.58003456 0.53618912 0.74407251 0.55318187]


In [68]:
arr=np.random.rand(2,3)
print(arr)

[[0.31328655 0.04485016 0.48171943]
 [0.35604491 0.25916083 0.73935251]]


In [77]:
arr2d=np.random.randint(1,10,15)
print(arr2d)

[2 4 4 7 1 6 1 4 9 1 9 8 1 6 8]


In [79]:
a=np.array([1,2,3,4])
print(np.sum(a))

10


In [86]:
a=np.array([[1,2],[3,4]])
print(np.sum(a,axis=0))

[4 6]


In [87]:
a.T

array([[1, 3],
       [2, 4]])

In [93]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
np.stack((a,b),axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [96]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=np.stack((a,b),axis=1)
print(c)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [100]:
d=c.reshape(2,4)
print(d)

[[1 1 2 2]
 [3 3 4 4]]


In [104]:
e=c.reshape(8,)
print(e)

[1 1 2 2 3 3 4 4]


In [110]:
e.reshape(-1,4)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [125]:
a=np.array([1,2,3,4])
print(np.mean(a))
print(np.median(a))
print(a.max())
print(np.std(a))

2.5
2.5
4
1.118033988749895


In [123]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.ravel(a)

array([1, 2, 3, 4])

In [124]:
np.ravel(b)

array([5, 6, 7, 8])